### ISSUE TITLE
Lobby Team Selection

### ISSUE THREAD

**Issue by Klaudiaa11** [Maximalist-Corrin/WyrdWatersPublicTest#18]
Group of 4 players, in shared lobby:
When selecting a team in lobby menu screen, all players experienced issue in selecting a team they wanted to play in. 
Upon selection, it automatically generated a team number higher than what you have selected. i.e. selecting 'Team 2', the selected field would change to 'Team 3' instead.

**Comment by earthpwnjim** [comment]
I assume that someone is adding an extra 1 to account for array indexing when finding the selection that was clicked when choosing your team number

**Comment by Klaudiaa11** [comment]
> I assume that someone is adding an extra 1 to account for array indexing when finding the selection that was clicked when choosing your team number

Thanks! Worth double checking this in another gameplay then.
