### ISSUE TITLE
Control of the ships movement seems different to other people

### ISSUE THREAD

**Issue by earthpwnjim** [Maximalist-Corrin/WyrdWatersPublicTest#21]
https://file.io/j1SUg6yuISjM

My mouse doesn't control movement, only the position of the camera and then I can right click to go to the centre of the camera, is that right? Because I cant get to the edges of the map, as the camera doesn't over pan off the map to get the edge of the map in the centre of the screen.

I have an Nvidia 3070, an AMD 5600X and a 23" 1080p (1920x1080px) monitor.

I would expect the position of the mouse to control the movement, so that I can just place it where I want to go, but it only lets me set the "destination" as where the centre of my screen is.

It happens in all games, whether I am in a lobby by myself or with others. I can provide more specs or talk you through what's happening on Discord if you prefer.

Build 0.0776

**Comment by Maximalist-Corrin** [comment]
AH! THANK YOU! I totally forgot to remove some legacy code, I'm betting you have a controller plugged in?

**Comment by earthpwnjim** [comment]
I do indeed have a controller plugged in, that makes a lot of sense now! Thanks for the update,
