### ISSUE TITLE
Vanishing Boat - Build 0.0773

### ISSUE THREAD

**Issue by SoggyMousepad** [Maximalist-Corrin/WyrdWatersPublicTest#4]
### Disappearing Boat Bug - Wyrd Waters
Game runs as normal when boat disappears, just ghosting for a short amount of time/falling through the map.

 | ✨ | ‼️ |
| --- | --- |
| **Environment** | Windows 11 - Build 24H2 |
| **Device Specifications** | I5-12600KF, RTX 4060, 16GB |

| Game Info | Amount |
| --- | --- |
| **Player Count** | 1 (One) |
| **Boats Purchased & Count** | 2 (Two, Scout & Ramming ships) |

**Steps to Reproduction**

Just turn amongst rocks/islands.... Apparently? Happening shortly after to the second boat being destroyed by reaching the border of the map

**VIDEO**

https://github.com/user-attachments/assets/815de760-4bc5-440f-8950-e3207a70448f

**Comment by SoggyMousepad** [comment]
Apologies, forgot to label & assign :)

**Comment by Maximalist-Corrin** [comment]
> Apologies, forgot to label & assign :)

Not a problem

**Comment by AaronReddish** [comment]
I also received the same disappearing ram heading between same passage way

**Comment by TomWilkinsonGames** [comment]
Also having this issue.
Found this same issue when turning on the whirlpool map next to the rocks in the bottom left.
Perhaps this is an issue across all landmass sprites.

2.2. Method:
Launch game
Join lobby
Select small map
Start game
Sail close to bottom left rocks on map

Expected: Nothing, sail by rocks.
What happened: Boat sprite disappeared.

https://github.com/user-attachments/assets/dfe69330-55c9-4e76-8a31-324716002700

Environment: 4 player game on small map

Platform: PC, Steam Wyrd Waters, Build 0.0776

Operating System: Windows 10

Hardware: MSI Laptop, 1080x1920 Monitor, Geforce GTX1050, Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz , 16GB RAM

2.6
Low priority
